### ISSUE TITLE
Feature request: "Light" should list rooms in addition to the individual lamps

### ISSUE THREAD

**Issue by olewolf** [chadwpalm/Lumunarr#1]
The server behaviors currently list the individual lights. However, lights may also be arranged in rooms. They should be listed, too, so that an entire group of lamps may be controlled with a single behavior. (If I remember correctly, the Hue API allows you to specify either single lights or groups, so this feature is probably minimal effort.)

**Comment by chadwpalm** [comment]
Server alerts started out as a novelty item that I ended up expanding on and leaving in the app. The Plex apps for mobile allow notifications for these same functions, so I wasn't sure if people would actually be using them.

I chose to use individual lights because it was weird to me to have all the lights in a room blink for an alert rather than just one, so it was purely a choice of design rather than effort. Since you aren't the only one who has expressed an interest in expanding from one light to many, I'll throw this in the to-do list for a future update.

**Comment by chadwpalm** [comment]
I have rolled this feature into v1.5.0. An option in the Lights pulldown in both Server behaviors allow you to select All which will turn on or blink all of the lights in the room/zone that is selected.

I will go ahead and close this issue.
