### ISSUE TITLE
Option to disable the Lumunarr scene transition time

### ISSUE THREAD

**Issue by pir8radio** [chadwpalm/Lumunarr#31]
Option to disable the Lumunarr scene transition time.  All of my hue scenes already have transition times set. For example my play scene dims the lights over 5 seconds, where my stop scene brings the lights back to full over 60 seconds so you aren't blinded.  Lumunarr's transition is overwriting mine and I'm forced to keep the same transitions for all actions..   wouldn't be as bad if each scene had its own transition slider in Lumunarr.

**Comment by chadwpalm** [comment]
Good catch. Lumunarr does edit the transition time of a scene before recalling it and I didn't consider the edge case that someone may have set those times to their liking in a different app. You are the first to mention doing this, so I suppose necessity really is the mother of invention :)

I can definitely add a "default" option to the transition time and have it also make that the default when creating new client profiles.

I'm out of town at the moment, so I prob won't be able to make this change until later this week. In the meantime, a temporary workaround could be that you create multiple client profiles with the same client and user and set the transition time for just the scenes/actions you want and set the other actions as "none", then do the same for the other client profiles. This is how I would suggest doing it anyway if users wanted different transition times (and didn't set defaults in another app) since it is global to the profile and not settable for each scene.

I'll get started on the update this week and let you know when I have it reading for you to test. 

Chad

**Comment by pir8radio** [comment]
no need for me to mess with the work around..   I'll wait for whatever you come up with. happy to test it!   Since im probably a rare case where i have transition times already set,   maybe it would be better to have each (play, stop, pause) have their own transition times so your fix would work for everyone?   But i'm happy with either lol... Just thinking what would benefit others. 

Thanks Chad!!!

**Comment by chadwpalm** [comment]
@pir8radio 

You mentioned in your first post "All of my hue scenes already have transition times set."

What app are you using to set them? I'd like to mimic it so I can test locally before pushing anything out.

Thanks.

**Comment by pir8radio** [comment]
> @pir8radio
> 
> You mentioned in your first post "All of my hue scenes already have transition times set."
> 
> What app are you using to set them? I'd like to mimic it so I can test locally before pushing anything out.
> 
> Thanks.

https://apps.apple.com/us/app/hue-lights/id762009425          is the app.. but again, for people without a third party app, im cool with your app having multiple transition time inputs,  but this is probably easier  :-)

**Comment by chadwpalm** [comment]
Yeah, it's a matter of how much I want to clutter up the interface. Transition times for each action would make the editor longer and require a lot more development work since each one would need a new entry in the settings file.

I think if people want different transition times for each action they can either do what I suggested above with using different client profiles, or set the transition time to "default" (which I will add) and can use a third-party app to set them.

I have an Android phone and it looks like that app doesn't exist for Android, so I'll just have to push a feature branch and have you test for me.

Chad

**Comment by pir8radio** [comment]
> Yeah, it's a matter of how much I want to clutter up the interface. Transition times for each action would make the editor longer and require a lot more development work since each one would need a new entry in the settings file.
> 
> I think if people want different transition times for each action they can either do what I suggested above with using different client profiles, or set the transition time to "default" (which I will add) and can use a third-party app to set them.
> 
> I have an Android phone and it looks like that app doesn't exist for Android, so I'll just have to push a feature branch and have you test for me.
> 
> Chad

sounds good, its your baby...   Just feel bad doing something for pretty much me lol...   I guess others can use the same ios app I did...   :-)

**Comment by chadwpalm** [comment]
@pir8radio 

I've created a new tag in Docker Hub called "fix-default-transition-1.4.4.87". Go ahead and respin your container with that tag and it should have the new fix.

On the transition time slider, if you go fully to the left it will set it to "Default" (Can be done globally in Settings as well). When set this way it shouldn't send a transition time when recalling the scene and in theory should use any transition time that is saved in the scene. Any newly created profiles should default to "Default" unless you change it. Existing times will remain.

Go ahead and give it a try when you can and let me know if that works.

Thanks,
Chad

**Comment by pir8radio** [comment]
> @pir8radio
> 
> I've created a new tag in Docker Hub called "fix-default-transition-1.4.4.87". Go ahead and respin your container with that tag and it should have the new fix.
> 
> On the transition time slider, if you go fully to the left it will set it to "Default" (Can be done globally in Settings as well). When set this way it shouldn't send a transition time when recalling the scene and in theory should use any transition time that is saved in the scene. Any newly created profiles should default to "Default" unless you change it. Existing times will remain.
> 
> Go ahead and give it a try when you can and let me know if that works.
> 
> Thanks, Chad

😁 I don't use docker.   am i able to dl and rebuild?

**Comment by chadwpalm** [comment]
> 😁 I don't use docker. am i able to dl and rebuild?

Yeah, you can pull from the "fix-default-transition" branch and rebuild. You should be able to keep the same settings.js file.

**Comment by pir8radio** [comment]
great ill try here in a few mins..  finishing up some work on a project of my own..  I'm more of a python guy..  :-)

**Comment by pir8radio** [comment]
IT WORKS!    sweet... Thank you

**Comment by chadwpalm** [comment]
Thanks for testing! I'll go ahead and push it to the dev branch. If things look good after a week or two I'll push to main and close the issue.

**Comment by pir8radio** [comment]
I'll try to remember to give you an update, but I have the memory of a gold fish, so...  if you hear nothing assume its good!  :-)

**Comment by pir8radio** [comment]
still working as expected!  Thanks@@

**Comment by chadwpalm** [comment]
I've released the update to the main branch and I'll go ahead and close this issue. If any other issues related to this crop up, just let me know.
